---
## absolute path to the oetl-script
:pg:
 :host: localhost # 172.28.50.25 
 :port: 5432
:environment:
  :test:
    dbname: test
    user:  root
    pass:  root
  :development:
    dbname: devel
    user: root
    pass: root
  :production:
    dbname: production
    user: root
    pass: root
:admin:
  :host: localhost
  :port: 2480
  :user: root
  :pass: topo1focus
logger: stdout           # 'file' or 'stdout'

