require_relative "../lib/model/document.rb"
require_relative "../lib/model/revision_record.rb"
require_relative "../lib/model/vertex.rb"
require_relative "../lib/model/edge.rb"
require_relative "../lib/model/revision.rb"
require_relative "../lib/model/basicvertex.rb"
require_relative "../lib/model/basicdocument.rb"
require_relative "../lib/model/basicedge.rb"
