# RAG Use Case Integration Tests
#
# These tests demonstrate a complete RAG (Retrieval-Augmented Generation) workflow
# using realistic knowledge base data. The tests cover:
# - Document ingestion with embeddings
# - Vector similarity search
# - Hybrid search (vector + full-text)
# - Category-based filtering
# - Real-world query scenarios
#
# This mimics the graph-rag demo pattern from:
# https://github.com/ArcadeData/arcadedb-usecases/blob/main/graph-rag

require 'spec_helper'
require 'arcade/rag_schema'

# Helper module for generating mock embeddings
module RagTestHelpers
  ##
  # Generate a deterministic mock embedding for testing purposes
  # In production, this would be generated by an embedding model
  #
  # @param text [String] Text to embed
  # @param seed [Integer] Seed for deterministic generation
  # @return [Array<Float>] 1536-dimensional vector
  def self.generate_mock_embedding(text, seed: 42)
    base_hash = (text + seed.to_s).hash
    vector = []
    1536.times do |i|
      value = ((base_hash * (i + 1) * 31) % 10000) / 10000.0 - 0.5
      vector << value
    end
    vector
  end
end

RSpec.describe 'RAG UseCase Integration Tests', order: :defined do
  let(:sample_embedding) { Array.new(1536) { rand } }

  before(:all) do
    # Set logger level to WARN to reduce output

    # Ensure test database is ready
    databases = Arcade::Api.databases
    Arcade::Api.drop_database Arcade::Config.database[:test] if databases.include?(Arcade::Config.database[:test])
    Arcade::Api.create_database Arcade::Config.database[:test]
    Arcade::Init.connect :test

    Arcade::Database.logger.level = Logger::WARN
    # Create the type with RAG schema
    UseCase::KnowledgeDocument.create_type
  end

  after(:all) do
    # Cleanup: drop the test type
    UseCase::KnowledgeDocument.drop_type rescue nil
  end

  describe 'Document Ingestion' do
    before(:all) do
      # Sample knowledge base documents - simulating technical documentation
      @documents = [
        {
          title: 'Introduction to Graph Databases',
          content: 'Graph databases are designed to store and treat relationships between data entities as first-class citizens. Unlike relational databases, graph databases use nodes and edges to represent and store data. This makes them ideal for analyzing complex relationships and patterns in data.',
          category: 'Database Fundamentals',
          tags: ['graph', 'database', 'nosql', 'fundamentals'],
          author: 'Database Team'
        },
        {
          title: 'ArcadeDB Overview',
          content: 'ArcadeDB is a multi-model graph database built from the ground up with support for vertices, edges, documents, arrays, and vectors. It provides a SQL-like query language and supports RAG (Retrieval-Augmented Generation) workloads with native vector search capabilities.',
          category: 'Database Systems',
          tags: ['arcadedb', 'graph', 'vector', 'rag'],
          author: 'ArcadeDB Team'
        },
        {
          title: 'Vector Search Fundamentals',
          content: 'Vector search, also known as semantic search, uses mathematical representations of data called embeddings. These embeddings capture the semantic meaning of text, allowing for similarity-based searches that understand context rather than just keyword matching.',
          category: 'Search Technology',
          tags: ['vector', 'embedding', 'similarity', 'ai'],
          author: 'AI Research Team'
        },
        {
          title: 'RAG Architecture Patterns',
          content: 'Retrieval-Augmented Generation (RAG) combines retrieval-based and generation-based approaches. It first retrieves relevant documents from a knowledge base using vector similarity, then uses a language model to generate responses based on the retrieved context.',
          category: 'AI Architecture',
          tags: ['rag', 'llm', 'retrieval', 'generation'],
          author: 'ML Engineering'
        },
        {
          title: 'SQL Query Optimization',
          content: 'Query optimization in SQL databases involves techniques like indexing, query planning, and execution strategy selection. Proper indexing strategies can dramatically improve query performance, especially for complex joins and aggregations.',
          category: 'Database Performance',
          tags: ['sql', 'optimization', 'indexing', 'performance'],
          author: 'Performance Team'
        },
        {
          title: 'NoSQL vs SQL Databases',
          content: 'NoSQL databases offer flexible schemas and horizontal scaling, making them suitable for unstructured data and high-velocity applications. SQL databases provide ACID transactions and structured querying capabilities. The choice depends on your specific use case requirements.',
          category: 'Database Comparison',
          tags: ['nosql', 'sql', 'comparison', 'architecture'],
          author: 'Architecture Team'
        },
        {
          title: 'Full-Text Search Implementation',
          content: 'Full-text search indexes allow for efficient text querying beyond simple LIKE matches. They support tokenization, stemming, and relevance scoring. Modern search engines combine full-text search with vector embeddings for hybrid search capabilities.',
          category: 'Search Technology',
          tags: ['fulltext', 'search', 'indexing', 'hybrid'],
          author: 'Search Team'
        },
        {
          title: 'Embedding Models for Text',
          content: 'Text embedding models like BERT, Sentence Transformers, and OpenAI embeddings convert text into dense vectors. These vectors capture semantic relationships, enabling tasks like semantic search, clustering, and similarity detection.',
          category: 'Machine Learning',
          tags: ['embedding', 'bert', 'nlp', 'transformers'],
          author: 'NLP Team'
        }
      ]

      # Insert all documents with mock embeddings
      @documents.each do |doc_data|
        embedding = RagTestHelpers.generate_mock_embedding(
          doc_data[:title] + ' ' + doc_data[:content]
        )
        UseCase::KnowledgeDocument.create(
          title: doc_data[:title],
          content: doc_data[:content],
          embedding: embedding,
          category: doc_data[:category],
          tags: doc_data[:tags],
          author: doc_data[:author],
          created_at: DateTime.now
        )
      end
    end

    after(:all) do
      # Clean up inserted documents
      UseCase::KnowledgeDocument.delete_all rescue nil
    end

    it 'ingests all documents successfully' do
      count = UseCase::KnowledgeDocument.count
      expect(count).to eq(@documents.length)
    end

    it 'preserves document metadata' do
      docs = Arcade::Init.db.query("SELECT FROM use_case_knowledge_document WHERE title = 'Introduction to Graph Databases'")
      # query returns an array of hashes directly
      expect(docs).to be_an(Array)
      expect(docs.count).to be > 0
      doc = docs.first
      # Access hash with symbol keys
      expect(doc[:category]).to eq('Database Fundamentals')
      expect(doc[:tags]).to include('graph', 'database')
      expect(doc[:author]).to eq('Database Team')
    end

    it 'stores embeddings correctly' do
      docs = Arcade::Init.db.query("SELECT FROM use_case_knowledge_document WHERE title = 'ArcadeDB Overview'")
      expect(docs).to be_an(Array)
      expect(docs.count).to be > 0
      doc = docs.first
      expect(doc[:embedding]).to be_an(Array)
      expect(doc[:embedding].length).to eq(1536)
    end
  end

  describe 'Vector Similarity Search' do
    it 'finds semantically similar documents' do
      # Query about graph databases
      query_embedding = RagTestHelpers.generate_mock_embedding(
        'What is a graph database and how does it work?'
      )

      results = UseCase::KnowledgeDocument.vector_search(
        query_embedding,
        limit: 5,
        threshold: 0.0
      )

      # Results should be an array of hashes with metadata
      expect(results).to be_an(Array)
      if results.any?
        expect(results.first).to be_a(Hash)
        expect(results.first[:title]).to be_present
        expect(results.first[:similarity]).to be_present
      end
    end

    it 'respects the limit parameter' do
      query_embedding = RagTestHelpers.generate_mock_embedding('database query optimization')
      results = UseCase::KnowledgeDocument.vector_search(query_embedding, limit: 3, threshold: 0.0)

      expect(results).to be_an(Array)
      expect(results.count).to be <= 3
    end

    it 'applies threshold filtering' do
      query_embedding = RagTestHelpers.generate_mock_embedding('machine learning embeddings')

      results_high = UseCase::KnowledgeDocument.vector_search(query_embedding, limit: 10, threshold: 0.9)
      results_low = UseCase::KnowledgeDocument.vector_search(query_embedding, limit: 10, threshold: 0.0)

      expect(results_high).to be_an(Array)
      expect(results_low).to be_an(Array)
      # Higher threshold should return fewer or equal results
      expect(results_high.count).to be <= results_low.count
    end

    it 'returns documents with similarity scores' do
      query_embedding = RagTestHelpers.generate_mock_embedding('vector search algorithms')
      results = UseCase::KnowledgeDocument.vector_search(query_embedding, limit: 5, threshold: 0.0)

      # Results should be hashes with similarity field
      expect(results).to be_an(Array)
      if results.any?
        expect(results.first[:similarity]).to be_present
      end
    end
  end

  describe 'Hybrid Search' do
    it 'combines vector and full-text search' do
      query_embedding = RagTestHelpers.generate_mock_embedding('database performance tuning')

      results = UseCase::KnowledgeDocument.hybrid_search(
        query_embedding,
        'optimization',
        limit: 10,
        vector_threshold: 0.0
      )

      expect(results).to be_an(Array)
    end

    it 'filters by text content' do
      query_embedding = RagTestHelpers.generate_mock_embedding('search technology')

      results = UseCase::KnowledgeDocument.hybrid_search(
        query_embedding,
        'Full-Text',
        limit: 10,
        vector_threshold: 0.0
      )

      # All results should contain "Full-Text" in title or content
      results.each do |doc|
        expect(doc[:title].to_s + ' ' + doc[:content].to_s).to match(/full[- ]?text/i)
      end
    end

    it 'handles exact phrase matching' do
      query_embedding = RagTestHelpers.generate_mock_embedding('RAG patterns')

      results = UseCase::KnowledgeDocument.hybrid_search(
        query_embedding,
        'Retrieval-Augmented Generation',
        limit: 10,
        vector_threshold: 0.0
      )

      # Just check we get an array back - the query may or may not find matches
      expect(results).to be_an(Array)
    end
  end

  describe 'Category-Based Filtering' do
    it 'filters documents by category' do
      docs = Arcade::Init.db.query("SELECT FROM use_case_knowledge_document WHERE category = 'Search Technology'")

      expect(docs).to be_an(Array)
      docs.each do |doc|
        expect(doc[:category]).to eq('Search Technology')
      end
    end

    it 'combines category filter with vector search' do
      query_embedding = RagTestHelpers.generate_mock_embedding('database indexing')

      # First get category results
      docs = Arcade::Init.db.query("SELECT FROM use_case_knowledge_document WHERE category = 'Database Performance'")
      expect(docs).to be_an(Array)
    end

    it 'supports tag-based queries' do
      docs = Arcade::Init.db.query("SELECT FROM use_case_knowledge_document WHERE tags CONTAINS 'vector'")

      expect(docs).to be_an(Array)
      docs.each do |doc|
        expect(doc[:tags]).to include('vector')
      end
    end
  end

  describe 'Real-World Query Scenarios' do
    it 'handles "what is" questions' do
      query_embedding = RagTestHelpers.generate_mock_embedding(
        'What is ArcadeDB?'
      )

      results = UseCase::KnowledgeDocument.vector_search(query_embedding, limit: 3, threshold: 0.0)
      expect(results).to be_an(Array)
    end

    it 'handles comparison queries' do
      query_embedding = RagTestHelpers.generate_mock_embedding(
        'difference between SQL and NoSQL databases'
      )

      results = UseCase::KnowledgeDocument.vector_search(query_embedding, limit: 5, threshold: 0.0)
      expect(results).to be_an(Array)
    end

    it 'handles technical how-to queries' do
      query_embedding = RagTestHelpers.generate_mock_embedding(
        'How to optimize database queries with indexes?'
      )

      results = UseCase::KnowledgeDocument.hybrid_search(
        query_embedding,
        'indexing',
        limit: 5,
        vector_threshold: 0.0
      )

      expect(results).to be_an(Array)
    end

    it 'handles concept exploration queries' do
      query_embedding = RagTestHelpers.generate_mock_embedding(
        'Explain RAG architecture and its benefits'
      )

      results = UseCase::KnowledgeDocument.vector_search(query_embedding, limit: 5, threshold: 0.0)
      expect(results).to be_an(Array)
    end
  end

  describe 'Edge Cases' do
    it 'handles empty result sets gracefully' do
      # Query with very high threshold that likely won't match
      query_embedding = RagTestHelpers.generate_mock_embedding('quantum computing')
      results = UseCase::KnowledgeDocument.vector_search(query_embedding, limit: 10, threshold: 0.99)

      expect(results).to be_an(Array)
    end

    it 'handles queries with special characters' do
      query_embedding = RagTestHelpers.generate_mock_embedding('What is SQL? (Structured Query Language)')

      results = UseCase::KnowledgeDocument.hybrid_search(
        query_embedding,
        'SQL',
        limit: 5,
        vector_threshold: 0.0
      )

      expect(results).to be_an(Array)
    end

    it 'handles very short queries' do
      query_embedding = RagTestHelpers.generate_mock_embedding('DB')

      results = UseCase::KnowledgeDocument.vector_search(query_embedding, limit: 5, threshold: 0.0)
      expect(results).to be_an(Array)
    end

    it 'handles very long queries' do
      long_query = 'I am looking for information about database systems, specifically graph databases ' \
                   'that support vector search and can be used for RAG applications. I need something ' \
                   'that can handle complex queries and provide good performance for similarity search.'

      query_embedding = RagTestHelpers.generate_mock_embedding(long_query)
      results = UseCase::KnowledgeDocument.vector_search(query_embedding, limit: 5, threshold: 0.0)

      expect(results).to be_an(Array)
    end
  end

  describe 'Performance Characteristics' do
    it 'returns results within reasonable time' do
      query_embedding = RagTestHelpers.generate_mock_embedding('database performance')

      start_time = Time.now
      results = UseCase::KnowledgeDocument.vector_search(query_embedding, limit: 10, threshold: 0.0)
      elapsed = Time.now - start_time

      # Should complete within 5 seconds (adjust based on your environment)
      expect(elapsed).to be < 5.0
      expect(results).to be_an(Array)
    end

    it 'scales with result limit' do
      query_embedding = RagTestHelpers.generate_mock_embedding('search algorithms')

      time_1 = Time.now
      UseCase::KnowledgeDocument.vector_search(query_embedding, limit: 1, threshold: 0.0)
      elapsed_1 = Time.now - time_1

      time_10 = Time.now
      UseCase::KnowledgeDocument.vector_search(query_embedding, limit: 10, threshold: 0.0)
      elapsed_10 = Time.now - time_10

      # Larger limits may take slightly longer but should be comparable
      expect(elapsed_10).to be < (elapsed_1 * 10)
    end
  end

  describe 'Schema Validation' do
    it 'has vector index configured' do
      indexes = Arcade::Init.db.indexes(true)
      # Look for vector index on our type
      vector_index = indexes.find do |idx|
        idx[:typeName].to_s.downcase == 'use_case_knowledge_document' &&
        idx[:type] == 'LSM_VECTOR'
      end

      expect(vector_index).to be_present
    end

    it 'has metadata index configured' do
      indexes = Arcade::Init.db.indexes(true)
      # Look for metadata LSM_TREE index on our type
      metadata_index = indexes.find do |idx|
        idx[:typeName].to_s.downcase == 'use_case_knowledge_document' &&
        idx[:type] == 'LSM_TREE'
      end

      expect(metadata_index).to be_present
    end
  end
end
